import { test, expect } from '@playwright/test';
import * as allure from "allure-js-commons";
import { Common } from '../page-objects/common';
import exp from 'constants';


test('Verify the application logo is updated.', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Verify the application logo is updated. ');await allure.owner('Sneha Krishna');await allure.tags('Signin','UI/UX');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await expect(page.getByRole('img', { name: 'Logo' })).toBeVisible()

  await page.getByRole('img', { name: 'Logo' }).click();
});


test('Confirm that the header of the login page displays the text login to event client console .', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Confirm that the header of the login page displays the text login to event client console. ');await allure.owner('Sneha Krishna');await allure.tags('Signin','UI/UX');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await expect(page.getByText('Login to Event Client Console')).toBeVisible()
  await page.getByText('Login to Event Client Console').click();
});


test('Check if the email input field has Email as its label and Enter your email as its placeholder.', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Check if the email input field has Email as its label and Enter your email as its placeholder. ');await allure.owner('Sneha Krishna');await allure.tags('Signin','UI/UX');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await expect(page.getByRole('textbox', { name: 'Enter your email' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
});

test('Check if the password input field has Password as its label and Enter your password as its placeholder.', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Check if the password input field has Password as its label and Enter your password as its placeholder. ');await allure.owner('Sneha Krishna');await allure.tags('Signin','UI/UX');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await expect(page.getByRole('textbox', { name: 'Enter your password' })).toBeVisible()
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
});

test('Confirm that the login CTA button displays Sign In and has the specified color.', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Confirm that the login CTA button displays Sign In and has the specified color.');await allure.owner('Sneha Krishna');await allure.tags('Signin','UI/UX');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await expect(page.getByRole('button', { name: 'Sign In' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign In' }).click();
});

test('Ensure that there is no Register button or link visible on the login page.', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Ensure that there is no Register button or link visible on the login page.');await allure.owner('Sneha Krishna');await allure.tags('Signin','UI/UX');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await expect(page.getByText('EmailPasswordSign In')).toBeVisible()
  await page.getByText('EmailPasswordSign In').click();
});

test('Verify that a user can successfully log in with valid credentials.', async ({ page }) => {await allure.feature('Signin');await allure.displayName('Verify that a user can successfully log in with valid credentials.');await allure.owner('Sneha Krishna');await allure.tags('Signin','Login validation');await allure.severity('High');await allure.parentSuite('Signin');await allure.suite('Login validation');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
});



test('Confirm that only the Account Call-To-Action CTA is present in its designated area and no other interactive elements occupy this space.', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Confirm that only the Account Call-To-Action CTA is present in its designated area and no other interactive elements occupy this space.');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('button', { name: 'n Account' }).click();
});

test('Ensure that tapping the Account CTA triggers the existing behavior of displaying the logout option.', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Ensure that tapping the Account CTA triggers the existing behavior of displaying the logout option.');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('button', { name: 'n Account' }).click();
});

test('Confirm the header with the text Select a project to continue is displayed in the top of the middle section and is centered aligned.', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Confirm the header with the text Select a project to continue is displayed in the top of the middle section and is centered aligned.');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByText('Select a project to continue').click();
});




test('Verify Main Navigation Layout Change to Vertical', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify Main Navigation Layout Change to Vertical');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
});

test('Verify REVOLT Logo Update and Top-Left Placement', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify REVOLT Logo Update and Top-Left Placement');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('img', { name: 'Logo' }).first().click();
});

test('Verify Account Access Relocation to Navigation Bottom', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify Account Access Relocation to Navigation Bottom');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('button', { name: 'n Account' }).click();
});

test('Verify Active Tab UI - Push Notifications', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify Active Tab UI - Push Notifications');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('tab', { name: 'Push Notification' }).click();
});

test('Verify Default Active Tab on First Entry - Push Notifications', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify Default Active Tab on First Entry - Push Notifications');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.locator('.AllNotification_page__D-78m').click();
});

test('Verify Default Inactive Tab on First Entry - Program Notifications', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify Default Inactive Tab on First Entry - Program Notifications');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
});

test('Verify CTA UI matches Figma design', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify CTA UI matches Figma design');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('tab', { name: 'Program Notification' }).click();
  await page.locator('.EventNotification_page__G4wFA').click();
  await page.getByRole('tab', { name: 'Push Notification' }).click();
  await page.locator('.AllNotification_page__D-78m').click();
});

test('Verify the Create Talent Form UI is accessible and displayed correctly.', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify the Create Talent Form UI is accessible and displayed correctly.');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Back to Talents|Create New TalentDraft Cancel Publish').click();
});

test('Verify Name field accepts valid input.', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify Name field accepts valid input.');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByText('SaturdayCreate New').click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Back to Talents|Create New TalentDraft Cancel Publish').click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('S');
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('Sneha');
  await page.locator('div').filter({ hasText: 'Basic InformationName *' }).nth(3).click();
  await page.getByRole('checkbox', { name: 'Saturday' }).check();
  await page.locator('.CreateTalent_dropIcon__VdaDr > svg').click();
  await page.locator('.MediaLibrary_folderIcon__XW9Br > svg').first().click();
  await page.getByRole('img', { name: 'VERIZON.png' }).click();
});



test('Verify profile picture selection control exists and is clickable.', async ({ page }) => {await allure.feature('Project listing');await allure.displayName('Verify profile picture selection control exists and is clickable.');await allure.owner('Sneha Krishna');await allure.tags('Project listing','UI/UX');await allure.severity('High');await allure.parentSuite('Project listing');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByText('SaturdayCreate New').click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Back to Talents|Create New TalentDraft Cancel Publish').click();
  await page.getByText('Profile Picture *').click();
  await page.locator('.CreateTalent_dropIcon__VdaDr > svg').click();
  await page.getByRole('button', { name: '×' }).click();
});

test('Verify navigation behavior when clicking links in the web application.', async ({ page }) => {await allure.feature('Main Navigation');await allure.displayName('Verify navigation behavior when clicking links in the web application.');await allure.owner('Sneha Krishna');await allure.tags('Main Navigation','UI/UX');await allure.severity('High');await allure.parentSuite('Main Navigation');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://d3u9vqdsad8fty.cloudfront.net/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
});



test('Verify image crop interface appears after selection.', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Verify image crop interface appears after selection.');await allure.owner('Sneha Krishna');await allure.tags('Talents','UI/UX');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByText('SaturdayCreate New').click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Back to Talents|Create New TalentDraft Cancel Publish').click();
  await page.locator('.CreateTalent_dropIcon__VdaDr > svg > path:nth-child(2)').click();
  await page.locator('.MediaLibrary_folderIcon__XW9Br > svg').first().click();
  await page.getByRole('img', { name: 'VERIZON.png' }).click();
  await page.locator('.CropModel_cropOverlay__bUAff').click();
});



test('Verify navigation to Configuration menu and initial display of tabs.', async ({ page }) => {await allure.feature('Configuration');await allure.displayName('Verify navigation to Configuration menu and initial display of tabs.');await allure.owner('Sneha Krishna');await allure.tags('Configuration','Tracks');await allure.severity('High');await allure.parentSuite('Configuration');await allure.suite('Tracks');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
});

test('Verify Tracks tab content display.', async ({ page }) => {await allure.feature('Configuration');await allure.displayName('Verify Tracks tab content display.');await allure.owner('Sneha Krishna');await allure.tags('Configuration','Tracks');await allure.severity('High');await allure.parentSuite('Configuration');await allure.suite('Tracks');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByRole('tab', { name: 'Tracks' }).click();
  await page.getByRole('textbox', { name: 'Enter Track name (e.g.,' }).click();
});

test('Configuration Menu Item Visibility', async ({ page }) => {await allure.feature('Configuration');await allure.displayName('Configuration Menu Item Visibility');await allure.owner('Sneha Krishna');await allure.tags('Configuration','Locations');await allure.severity('High');await allure.parentSuite('Configuration');await allure.suite('Locations');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.Projects_cardImage__IYNfF').first().click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByRole('tab', { name: 'Locations' }).click();
});


test('Initial Display after Configuration Selection', async ({ page }) => {await allure.feature('Configuration');await allure.displayName('Initial Display after Configuration Selection');await allure.owner('Sneha Krishna');await allure.tags('Configuration','Locations');await allure.severity('High');await allure.parentSuite('Configuration');await allure.suite('Locations');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByRole('tab', { name: 'Locations' }).click();
  await page.getByRole('tab', { name: 'Tracks' }).click();
});

test('Tracks Tab Selection and Dynamic Content Update', async ({ page }) => {await allure.feature('Configuration');await allure.displayName('Tracks Tab Selection and Dynamic Content Update');await allure.owner('Sneha Krishna');await allure.tags('Configuration','Locations');await allure.severity('High');await allure.parentSuite('Configuration');await allure.suite('Locations');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByText('LocationsTracks').click();
  await page.getByRole('tab', { name: 'Tracks' }).click();
  await page.getByText('LocationsTracks').click();
});

test('Locations Tab - Form and Empty State Visibility', async ({ page }) => {await allure.feature('Configuration');await allure.displayName('Locations Tab - Form and Empty State Visibility');await allure.owner('Sneha Krishna');await allure.tags('Configuration','Locations');await allure.severity('High');await allure.parentSuite('Configuration');await allure.suite('Locations');const common = new Common(page);
await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByRole('textbox', { name: 'Enter location name (e.g.,' }).click();
  await page.getByRole('textbox', { name: 'Enter deep link URL.' }).click();
});


test('Verify the display and non-interactivity of the screen name.', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify the display and non-interactivity of the screen name.');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Listing');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Listing');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Sponsors', exact: true }).click();
});

test('Verify the visibility and positioning of the Create New Call To Action (CTA).', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify the visibility and positioning of the Create New Call To Action (CTA).');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Listing');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Listing');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('img').nth(2).click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
});

test('Verify the navigation functionality of the Create New CTA.', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify the navigation functionality of the Create New CTA.');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Listing');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Listing');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('img').nth(2).click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Back to Sponsors|Create New SponsorDraft Cancel Publish').click();
  await page.getByText('Create New Sponsor').click();
});

test('Verify the visibility and text of the Select All feature.', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify the visibility and text of the Select All feature.');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Listing');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Listing');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByText('Sponsors 12 itemsCreate New').click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('checkbox').first().uncheck();
});

test('Verify Change CTA functionality after image upload.', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify Change CTA functionality after image upload.');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Create/Edit');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Create/Edit');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.locator('label').filter({ hasText: 'Click to upload or select' }).locator('svg').click();
  await page.getByText('ad-images').click();
  await page.getByRole('img', { name: 'VERIZON.png' }).click();
  await page.getByText('Change', { exact: true }).click();
});

test('Verify the Home screen sponsor toggle functionality ON.', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify the Home screen sponsor toggle functionality (ON).');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Create/Edit');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Create/Edit');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
});

test('Verify the Home screen sponsor toggle functionality OFF.', async ({ page }) => {await allure.feature('Sponsor');await allure.displayName('Verify the Home screen sponsor toggle functionality (OFF).');await allure.owner('Sneha Krishna');await allure.tags('Sponsor','Create/Edit');await allure.severity('High');await allure.parentSuite('Sponsor');await allure.suite('Create/Edit');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
});

test('Verify the display and alignment of the section title Participants & Sponsors', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Verify the display and alignment of the section title Participants & Sponsors');await allure.owner('Sneha Krishna');await allure.tags('Programming','Participants/sponsors');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Participants/sponsors');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Participants & Sponsors').click();
});

test('Verify navigation upon clicking the Create New CTA.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Verify navigation upon clicking the Create New CTA.');await allure.owner('Sneha Krishna');await allure.tags('Programming','Table creation');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Table creation');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.comT');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Sponsors Sponsors' }).click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Create New Program').click();
});

test('Verify the presence and alignment of the Select All feature.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Verify the presence and alignment of the Select All feature.');await allure.owner('Sneha Krishna');await allure.tags('Programming','Table creation');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Table creation');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  const checkbox = page.getByRole('checkbox').nth(1);
  await checkbox.click();
  await page.getByRole('checkbox').nth(1).uncheck();
});

test('Verify Status Filters Appearance - With Talent', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Verify Status Filters Appearance - With Talent');await allure.owner('Sneha Krishna');await allure.tags('Programming','Functionality');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Functionality');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByText('SaturdayCreate New').click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('textbox', { name: 'Enter program title' }).click();
  await page.getByRole('textbox', { name: 'Enter program title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter program title' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter program title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter program title' }).fill('Test12');
  await page.locator('label').filter({ hasText: 'Click to upload or select' }).locator('svg').click();
  await page.getByText('ad-images').click();
  await page.getByRole('img', { name: 'VERIZON.png' }).click();
  await page.getByText('Select day').click();
  await page.getByText('Saturday').click();
  await page.getByRole('spinbutton', { name: 'Hours' }).first().click();
  await page.getByRole('button', { name: 'Choose time' }).first().click();
  await page.getByRole('option', { name: 'AM' }).click();
  await page.getByText(':00 AM').click();
  await page.getByText('hh').click();
  await page.getByRole('button', { name: 'Choose time', exact: true }).click();
  await page.getByRole('option', { name: '10 minutes' }).click();
  await page.getByText(':10 AM').click();
  await page.getByRole('checkbox').first().check();
  await page.getByText('Location *').click();
  await page.getByText('Select location').click();
  await page.getByText('Bodega-gs').click();
  await page.locator('div').filter({ hasText: 'Basic InformationTitle *' }).nth(4).click();
  await page.getByText('Back to Programming|Test12Draft Cancel Publish').click();
  await page.getByRole('button', { name: 'Back to Programming' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Unpublish' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('SaturdayCreate New').click();
});


test('Verify Headliner Filter Appearance', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Verify Headliner Filter Appearance');await allure.owner('Sneha Krishna');await allure.tags('Programming','Functionality');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Functionality');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('checkbox').first().uncheck();
  await page.getByText('Published', { exact: true }).click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('checkbox').first().uncheck();
  await page.getByText('Unpublished').click();
  await page.getByRole('checkbox').first().check();
  await page.getByRole('checkbox').first().uncheck();
  await page.getByText('Draft').click();
});

test('Verify Select All Feature Appearance', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Verify Select All Feature Appearance');await allure.owner('Sneha Krishna');await allure.tags('Programming','Functionality');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Functionality');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('checkbox').nth(1).uncheck();
  await page.getByText('Published', { exact: true }).click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('checkbox').nth(1).uncheck();
  await page.getByText('Unpublished').click();
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('checkbox').nth(1).uncheck();
  await page.getByText('Draft').click();
});


test('Action CTA - Unpublish for Published Talent', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Verify that for a published talent, Unpublish CTA is available, and clicking it unpublishes the talent.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Talents');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Talents');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('T');
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('Test12');
  await page.getByRole('checkbox', { name: 'Saturday' }).check();
  await page.locator('.CreateTalent_dropIcon__VdaDr > svg > path:nth-child(2)').click();
  await page.locator('div:nth-child(2) > .MediaLibrary_folderIcon__XW9Br > svg > path:nth-child(2)').click();
  await page.getByRole('img', { name: 'BlackCoffeeCafe.png' }).click();
  await page.getByRole('img', { name: 'BlackCoffeeCafe.png' }).click();
  await page.getByRole('button', { name: 'Apply Crop' }).click();
  await page.getByRole('button', { name: 'Back to Talents' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Unpublish' }).click();
  await page.getByText('Unpublished').click();
});



test('Verify Schedule Modal appearance and background', async ({ page }) => {await allure.feature('Schedule');await allure.displayName('Ensure the Schedule Modal appears correctly with a darkened background when Schedule is tapped.');await allure.owner('Sneha Krishna');await allure.tags('Schedule','UI/UX');await allure.severity('High');await allure.parentSuite('Schedule');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.locator('body').press('ControlOrMeta+-');
  await page.locator('body').press('ControlOrMeta+-');
  await page.locator('body').press('ControlOrMeta+-');
  await page.locator('body').press('ControlOrMeta+-');
  await page.locator('body').press('ControlOrMeta+-');
  await page.locator('body').press('ControlOrMeta+-');
  await page.getByRole('button', { name: 'Schedule' }).click();
  await page.getByRole('button', { name: 'Schedule Notification' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.locator('.AllNotification_page__D-78m').click();
});

test('Verify the presence and position of the Notification Log tab.', async ({ page }) => {await allure.feature('Schedule');await allure.displayName('Ensure that the Notification Log tab is present on the UI and is positioned to the right of the Program Notifications tab in the middle section.');await allure.owner('Sneha Krishna');await allure.tags('Schedule','List');await allure.severity('High');await allure.parentSuite('Schedule');await allure.suite('List');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('tab', { name: 'Notification Log' }).click();
});


test('Verify Form Title for creating a new program.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Ensure that when creating a new program, the form title correctly displays Create New Program');await allure.owner('Sneha Krishna');await allure.tags('Programming','Create');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Create');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
});


test('Verify Schedule section title and field labels.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Ensure the Schedule section title is present and left-aligned, along with correct field names and mandatory asterisks.');await allure.owner('Sneha Krishna');await allure.tags('Programming','Create');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Create');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Schedule', { exact: true }).click();
  await page.getByText('Location *').click();
  await page.getByText('Participants & Sponsors').click();
  await page.getByText('Call to Action').click();
});


test('Verify the Calendar View toggle is active on initial load.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Ensure that when navigating to the program calendar, the Calendar view toggle is highlighted or marked as active, while the Listing toggle is inactive.');await allure.owner('Sneha Krishna');await allure.tags('Programming','Calendar');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Calendar');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Calendar View' }).click();
});

test('Verify Select All feature presence and position in Calendar View.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Ensure the Select All checkbox and accompanying text are correctly displayed below the day tabs, left-aligned in the Calendar View.');await allure.owner('Sneha Krishna');await allure.tags('Programming','Calendar');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Calendar');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Notifications Notifications' }).click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Calendar View' }).click();
  const checkbox = page.getByRole('checkbox').first();

  await checkbox.click();
  await page.getByRole('checkbox').first().click();
  await page.getByRole('checkbox').first().uncheck();
});

test('Successfully create a new program with valid data.', async ({ page }) => {await allure.feature('Programming');await allure.displayName('Fill out all required and some optional fields in the Add Program form with valid data and save it.');await allure.owner('Sneha Krishna');await allure.tags('Programming','Create');await allure.severity('High');await allure.parentSuite('Programming');await allure.suite('Create');const common = new Common(page);
   await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Programming Programming' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('textbox', { name: 'Enter program title' }).click();
  await page.getByRole('textbox', { name: 'Enter program title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter program title' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter program title' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter program title' }).fill('Test12');
  await page.locator('path').nth(1).click();
  await page.locator('.MediaLibrary_folderIcon__ErVOG').first().click();
  await page.getByRole('img', { name: 'VERIZON.png' }).click();
  await page.getByText('Select day').click();
  await page.getByText('Saturday').click();
  await page.getByRole('spinbutton', { name: 'Hours' }).first().click();
  await page.getByRole('button', { name: 'Choose time' }).first().click();
  await page.getByRole('option', { name: 'AM' }).click();
  await page.getByText('hh').click();
  await page.getByText('hh').click();
  await page.getByRole('button', { name: 'Choose time', exact: true }).click();
  await page.getByRole('option', { name: '5 minutes', exact: true }).click();
  await page.getByText(':05 AM').click();
  await page.getByRole('checkbox').first().check();
  await page.locator('div').filter({ hasText: /^Select location$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Main Level$/ }).click();
  await page.getByRole('button', { name: 'Back to Programming' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Unpublish' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});

test('Verify Section Header on Program Notification form', async ({ page }) => {await allure.feature('Schedule');await allure.displayName('Ensure the Who should receive this notification? header is displayed correctly on the Program Notification creation form.');await allure.owner('Sneha Krishna');await allure.tags('Schedule','UI/UX');await allure.severity('High');await allure.parentSuite('Schedule');await allure.suite('UI/UX');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('tab', { name: 'Program Notifications' }).click();
});

test('Verify the successful addition of a new GPS Link field to the Locations Content Fragment Model.', async ({ page }) => {await allure.feature('Configurations');await allure.displayName('As a Content Fragment Model administrator, I need to add a new text field named GPS Link to the Locations Content Fragment Model to store GPS coordinates or a map link.');await allure.owner('Sneha Krishna');await allure.tags('Configurations','Locations');await allure.severity('High');await allure.parentSuite('Configurations');await allure.suite('Locations');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Configuration Configuration' }).click();
  await page.getByRole('textbox', { name: 'Enter location name (e.g.,' }).click();
  await page.getByRole('textbox', { name: 'Enter location name (e.g.,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter location name (e.g.,' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter location name (e.g.,' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter location name (e.g.,' }).fill('Test');
  await page.getByRole('textbox', { name: 'Enter deep link URL.' }).click();
  await page.getByRole('textbox', { name: 'Enter deep link URL.' }).click();
  await page.getByRole('textbox', { name: 'Enter deep link URL.' }).fill('https://www.facebook.com/');
  await page.getByRole('button', { name: 'Create' }).click();
  await page.goto('https://console.staging.revoltworld.com/configuration');
  await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByRole('checkbox').nth(1).check();
});


test('Verify navigation to Talent Listing screen via main navigation.', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Test that clicking the Talent link in the main navigation for a specific project successfully displays the Talent Listing screen.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Listing');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Listing');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
});

test('Verify navigation to Talent Form upon clicking Create New Talent CTA.', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Test that clicking the Create New Talent CTA button successfully navigates the user to the Talent Form screen.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Listing');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Listing');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
});


test('Initial navigation to Talent Listing screen', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Verify that clicking Talent on the main navigation leads to the Talent Listing screen, and the default view correctly displays content fragments from AEM.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Talents');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Talents');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByText('Create New Talent').click();
});

test('Back CTA functionality on Talent Form returning to previous screen', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Verify that the Back to Talents CTA correctly returns the user to the Talent listing screen, preserving the previous day tab.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Talents');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Talents');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('button', { name: 'Back to Talents' }).click();
});



test('Cancel CTA behavior - Draft new, empty form', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Verify that clicking Cancel on a new, empty form (Draft status) closes the form and does not create any Talent.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Talents');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Talents');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
});

test('Action CTA - Publish for New/Draft Talent', async ({ page }) => {await allure.feature('Talents');await allure.displayName('Verify that for a new or draft talent, only the Publish CTA is displayed, and clicking it saves and publishes the talent.');await allure.owner('Sneha Krishna');await allure.tags('Talents','Talents');await allure.severity('High');await allure.parentSuite('Talents');await allure.suite('Talents');const common = new Common(page);
  await page.goto('https://console.staging.revoltworld.com/login');
  await page.getByRole('textbox', { name: 'Enter your email' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).fill('naven.a@tringapps.com');
  await page.getByRole('textbox', { name: 'Enter your password' }).click();
  await page.getByRole('textbox', { name: 'Enter your email' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('T');
  await page.getByRole('textbox', { name: 'Enter your password' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Enter your password' }).fill('Test@123');
  await page.getByRole('img', { name: 'Toggle password' }).click();
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('div:nth-child(2) > .Projects_cardImage__IYNfF').click();
  await page.getByRole('button', { name: 'Talents Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('button', { name: 'Back to Talents' }).click();
  await page.getByRole('button', { name: 'Create New' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('T');
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('Test');
  await page.getByRole('checkbox', { name: 'Saturday' }).check();
  await page.locator('.CreateTalent_dropIcon__VdaDr > svg').click();
  await page.locator('.MediaLibrary_folderIcon__XW9Br').first().click();
  await page.getByRole('img', { name: 'VERIZON.png' }).click();
  await page.getByRole('button', { name: 'Apply Crop' }).click();
  await page.getByRole('button', { name: 'Back to Talents' }).click();
  await page.getByRole('checkbox').nth(2).check();
  await page.getByRole('button', { name: 'Publish', exact: true }).click();
  await page.getByText('Published', { exact: true }).click();
});
